server:
  port: 8080
  servlet:
    context-path: /
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/obosa?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Seoul&useSSL=true&verifyServerCertificate=false
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQLDialect
      use-new-id-generator-mappings: false
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    show-sql: true
    open-in-view: false

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          decriptor:
            sql:
              BasicBinder: TRACE